<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CodePosts.aspx.cs" Inherits="lab7.CodePosts" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <br />
<table border="0">
    <tr>
    <td>
    <asp:Label ID="LabelFindPost" runat="server" Text="Label">Должность</asp:Label><asp:TextBox ID="TextBoxFindPost" runat="server"></asp:TextBox>
        <asp:Button ID="ButtonFindPOst" runat="server" Text="Найти" OnClick="ButtonFindPost_Click" />
    <br />        
        <asp:GridView ID="GridViewPost" runat="server" AutoGenerateColumns="False"
            AllowPaging="True" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            OnRowCancelingEdit="GridViewPost_RowCancelingEdit" 
            OnRowDeleting="GridViewPost_RowDeleting" 
            OnRowEditing="GridViewPost_RowEditing" 
            OnRowUpdating="GridViewPost_RowUpdating" PageSize="15" 
            OnPageIndexChanging="GridViewPost_PageIndexChanging"
            Caption="Наименования должностей" 
            EmptyDataText="Нет данных" CaptionAlign="Top" PageIndex="0">
            <Columns>
                <asp:BoundField DataField="PostId" HeaderText="Код" SortExpression="PostId" />
                <asp:BoundField DataField="NameOfPost" HeaderText="Название" SortExpression="NameOfPost" />
            </Columns>
            
    </asp:GridView>
        </td>
        <td>
        <strong>Добавить новую должность:</strong>
            <br />
            <asp:label runat="server">Наименование должности:</asp:label><asp:TextBox ID="TextBoxNameOfPost" runat="server"></asp:TextBox>
            <br />
        </td>
        <td>
            <asp:Button ID="ButtonAddPost" runat="server" Text="Добавить" OnClick="ButtonAddPost_Click" />

        </td>
</tr>
</table>
    </asp:Content>