<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CodeTrains.aspx.cs" Inherits="lab7.CodeTrains" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <br />
<table border="0">
    <tr>
    <td>
    <asp:Label ID="LabelFindTrain" runat="server" Text="Label">Поезд</asp:Label><asp:TextBox ID="TextBoxFindTrain" runat="server"></asp:TextBox>
        <asp:Button ID="ButtonFindTrain" runat="server" Text="Найти" OnClick="ButtonFindTrain_Click" />
    <br />        
        <asp:GridView ID="GridViewTrain" runat="server" AutoGenerateColumns="False"
            AllowPaging="True" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            OnRowCancelingEdit="GridViewTrain_RowCancelingEdit" 
            OnRowDeleting="GridViewTrain_RowDeleting" 
            OnRowEditing="GridViewTrain_RowEditing" 
            OnRowUpdating="GridViewTrain_RowUpdating" PageSize="15" 
            OnPageIndexChanging="GridViewTrain_PageIndexChanging"
            Caption="Список поездов" 
            EmptyDataText="Нет данных" CaptionAlign="Top" PageIndex="0">
            <Columns>
                <asp:BoundField DataField="TrainId" HeaderText="Код" SortExpression="TrainId" />
                <asp:TemplateField HeaderText="Тип поезда" SortExpression="TypeId">
                <EditItemTemplate>
                    <asp:DropDownList ID="TypeIdDropDownList" runat="server" DataSourceID="SqlDataSourceType" DataTextField="NameOfType" DataValueField="TypeId" SelectedValue='<%# Bind("TypeId") %>'>
                    </asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                 <asp:Label ID="TypeId" runat="server"  Text='<%# Eval("NameOfType") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
                <asp:BoundField DataField="IsFirm" HeaderText="Фирменный ли" SortExpression="IsFirm" />
            </Columns>
            
    </asp:GridView>
        </td>
        <td>
        <strong>Добавить новый поезд:</strong>
            <br />
            <asp:label runat="server">Фирменный ли поезд:</asp:label><asp:TextBox ID="TextBoxIsFirm" runat="server"></asp:TextBox>
            <br />
            <br />
            Тип поезда
           <asp:DropDownList ID="TypeDropDownList" DataSourceID="SqlDataSourceType" DataValueField="TypeId" DataTextField="NameOfType" runat="server"></asp:DropDownList>
            <br />
            <asp:Button ID="ButtonAddTrain" runat="server" Text="Добавить" OnClick="ButtonAddTrain_Click" />
        </td>   
</tr>
</table>
    <asp:SqlDataSource ID="SqlDataSourceType" runat="server" 
        ConnectionString="<%$ ConnectionStrings:Course1ConnectionString %>" 
        SelectCommand="SELECT [TypeId], [NameOfType] FROM [Types]">
    </asp:SqlDataSource>
    </asp:Content>