<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="CodeTypes.aspx.cs" Inherits="lab7.CodeTypes" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <br />
<table border="0">
    <tr>
    <td>
    <asp:Label ID="LabelFindType" runat="server" Text="Label">Должность</asp:Label><asp:TextBox ID="TextBoxFindType" runat="server"></asp:TextBox>
        <asp:Button ID="ButtonFindPOst" runat="server" Text="Найти" OnClick="ButtonFindType_Click" />
    <br />        
        <asp:GridView ID="GridViewType" runat="server" AutoGenerateColumns="False"
            AllowPaging="True" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            OnRowCancelingEdit="GridViewType_RowCancelingEdit" 
            OnRowDeleting="GridViewType_RowDeleting" 
            OnRowEditing="GridViewType_RowEditing" 
            OnRowUpdating="GridViewType_RowUpdating" PageSize="15" 
            OnPageIndexChanging="GridViewType_PageIndexChanging"
            Caption="Наименования должностей" 
            EmptyDataText="Нет данных" CaptionAlign="Top" PageIndex="0">
            <Columns>
                <asp:BoundField DataField="TypeId" HeaderText="Код" SortExpression="TypeId" />
                <asp:BoundField DataField="NameOfType" HeaderText="Название" SortExpression="NameOfType" />
            </Columns>
            
    </asp:GridView>
        </td>
        <td>
        <strong>Добавить новый тип:</strong>
            <br />
            <asp:label runat="server">Наименование типа:</asp:label><asp:TextBox ID="TextBoxNameOfType" runat="server"></asp:TextBox>
            <br />
        </td>
        <td>
            <asp:Button ID="ButtonAddType" runat="server" Text="Добавить" OnClick="ButtonAddType_Click" />

        </td>
</tr>
</table>
    </asp:Content>
